config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :recipes
  resources :favorites
  resources :users
  get '/', to: 'static_pages#home', as: 'home'
  post '/ingredients/:id/add_to_cabinet', to: 'ingredients#add_to_cabinet', as: 'add_to_cabinet'
  post '/recipes/:id/add_to_favorites', to: 'recipes#add_to_favorites', as: 'add_to_favorites'
  get '/user/:id/what_can_i_make', to: 'users#what_can_i_make', as: 'what_can_i_make'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients, dependent: :destroy
  has_many :recipes, through: :recipe_ingredients
  has_many :user_ingredients, dependent: :destroy
  has_many :users, through: :user_ingredients

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :favorites
  has_many :users, through: :favorites
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  def self.search(search)
    if search
      results = self.select do |recipe|
        recipe.instructions.include?(search) || recipe.name.include?(search.titlecase) || recipe.ingredients.any? {|ing| ing.name.downcase.include?(search.downcase)}
      end
    else
      self.all
    end
  end

  def recommendations
    matches = Recipe.all.select do |recipe|
      recipe.ingredients.first == self.ingredients.first &&
      recipe.ingredients.second == self.ingredients.second
    end
   matches.delete_if{|r|r.name == self.name}
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :favorites
  has_many :recipes, through: :favorites
  has_many :user_ingredients
  has_many :ingredients, through: :user_ingredients
  validate :age
  validates :username, uniqueness: true
  validates :first_name, :last_name, presence: true
  validates_confirmation_of :password

  def full_name
    self.first_name + " " + self.last_name
  end

  def age
    now = Time.now.utc.to_date
    # now.year - self.birthdate.year - ((now.month > self.birthdate.month || (now.month == self.birthdate.month && now.day >= self.birthdate.day)) ? 0 : 1)
  end

  def over_21
    if self.age < 21
      errors.add(:birthdate, "Users must be 21 years of age or older to create an account")
    end
  end

  def what_can_i_make
    @my_recipes = Recipe.all.select do |recipe|
      recipe.ingredients - self.ingredients == []
    end
    @my_recipes
  end

  # def password=(password_text)
  #   self.password_digest = BCrypt::Password.create(password_text)
  # end
  #
  # def authenticate(password_text)
  #   if BCrypt::Password.new(self.password_digest) == password_text
  #     self
  #   else
  #     false
  #   end
  # end
end

app/models/user_ingredient.rb
class UserIngredient < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def login_user(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !!current_user
  end

  def authorized
    unless logged_in?
      flash[:notice] = "You must be logged in to see this page"
      redirect_to login_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  before_action :find_favorite, only: [:show]

  def index
    @favorites = Favorite.all
  end

  def show
  end

  def new
    @favorite = Favorite.new
  end

  def create
    byebug
    @favorite = Favorite.create(favorite_params)

    redirect_to favorites_path
  end

  def update
    byebug
    session[:recipe_id] = params[:recipe_id]
    flash[:message] = "You've successfully added this !"
    redirect_to recipes_path
  end

  private

  def find_favorite
    @favorite = Favorite.find(params[:id])
  end

  def favorite_params
    params.require(:favorite).permit(:user_id, :recipe_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :find_ingredient, only: [:show, :add_to_cabinet]

  def index
    @ingredients = Ingredient.all
  end

  def show
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.create(ingredient_params)

    if @ingredient.valid?
      redirect_to @ingredient
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def add_to_cabinet
    @user = current_user
    @user.ingredients << @ingredient
    redirect_to @user
  end


  private

  def find_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :find_recipe, only: [:show, :edit, :update, :destroy, :add_to_favorites]

  def index
    @favorites = Favorite.all
    @user = User.last
    if params[:search]
      @recipes = Recipe.search(params[:search])
    else
      @recipes = Recipe.all
    end
  end

  def show
    @recipes = Recipe.all
    @favorite = Favorite.new
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)

    if @recipe.valid?
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def add_to_favorites
    @user = current_user
    @user.recipes << @recipe
    redirect_to @user
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :occasion, :i1, :m1, :i2, :m2, :i3, :m3, :i4, :m4, :i5, :m5, :i6, :m6, :i7, :m7, :i8, :m8, :i9, :m9, :i10, :m10)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      login_user(@user)
      flash[:notice] = "Login successful! Welcome #{@user.username}"
      redirect_to user_path(@user)
    else
      flash[:notice] = 'Invalid username and/or password!'
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logout successful'
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy, :what_can_i_make]

  def index
  end

  def show
    @ingredients = @user.ingredients
    @favorites = @user.recipes
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.valid?
      redirect_to login_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
  end

  def what_can_i_make
    @recipes = @user.what_can_i_make
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :password, :birthdate)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.erb
<div class="index">
  <div class="layout">
  <h1>Ingredients</h1><br><br>
  <ul class="ing_list">
    <% @ingredients.each do |ingredient| %>
      <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li><br>
    <% end %>
  </ul>
    </div>
</div>

app/views/ingredients/show.erb
<div class="index">
<h1><%= @ingredient.name %></h1>
<hr>
<%= button_to 'Add to my cabinet', {action: 'add_to_cabinet'}, method: :post %>
</div>

app/views/recipes/index.erb
<div class="recipepage">
  <div class="content">
      <h1>Recipe Portal</h1>

      <div class="menu">
        <li><a href=<%= user_path(current_user) %> class="menuitem">Profile</a></li>
        <li><a href=<%= ingredients_path %> class="menuitem">Ingredients</a></li>
        <li> <%= link_to "Log out", logout_path, {method: :delete, :class=>"menuitem"} %> </li>
      </div>

      <div class="search">
        <%= form_tag recipes_path, method: :get do %>
          <%= text_field_tag(
              :search,
              params[:search],
              placeholder: "Search cocktails!",
          ) %>
          <%= submit_tag "Search" %>
        <% end %>
      </div><br>

      <p>
        Feel free to browse through our extensive collection of incredible cockatail
        recipes! Our database is updated regularly so you can continue to explore
        your current and future drinks of choice!
      </p><br>

      <h2>Collection of Cocktails 🍸</h2>

      <ul class="recipe-list">
        <% @recipes.each do |recipe| %>
        <li><%= link_to recipe.name, recipe_path(recipe) %></li><br>
        <% end %>
      </ul>
  </div>
</div>

app/views/recipes/show.erb
<div class="cocktail">

<div class="menu">
  <li><a href=<%= recipes_path %> class="menuitem">Back to all cocktails</a></li>
</div>

<h1><%= @recipe.name %></h1>

<!-- picture -->

<img src="<%= @recipe.img_url %>" alt=""><br><br>

Category: <%= @recipe.category %><br><br><br>
Instructions: <%= @recipe.instructions %><br><br><br>
Glassware: <%= @recipe.glass %><br><br><br>
Ingredients: <br><br>
<% @recipe.recipe_ingredients.each do |ing| %>
 <ul>
   <%= link_to "#{ing.measurement} #{ing.ingredient.name}", ingredient_path(Ingredient.find(ing.ingredient_id)) %>
 </ul>
<% end %>
<%= button_to "Add to FAVORITES", {action: 'add_to_favorites'}, method: :post %><br><br>
<% if @recipe.recommendations.length != 0 %>
 If you liked this, we recommend the following: <br><br>
 <% @recipe.recommendations.each do |recommendation| %>
   <ul>
     <%= link_to recommendation.name, recipe_path(recommendation) %>
   </ul>
 <% end %>
<% end %>

app/views/static_pages/home.erb
<div class="homepage">

  <h1 class="title">HOME BARTENDR 🍸</h1>

  <h2 class="subtitle">modern mixology for the bold // est. 2018</h2>

  <div class="menu">
    <li><a href=<%= login_path %> class="menuitem">Login</a></li>
    <li><a href=<%= new_user_path %> class="menuitem">Sign Up</a></li>
    <li><a href=<%= recipes_path %> class="menuitem">Cocktails</a></li>
    <li><a href=<%= ingredients_path %> class="menuitem">Ingredients</a></li>
    <li><a href="#" class="menuitem">Contact</a></li>
  </div>

  <p class="quote">
    "Here's to alcohol, the cause of, and solution to, all life's problems." <br>
    - The Simpsons
  </p>
</div>

app/views/users/_form.erb
<% if @user.errors.any? %>
  <p>Please correct the following errors before submitting:</p>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br><br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br><br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br><br>
  <%= f.label :birthdate %>
  <%= f.date_select :birthdate, start_year: 1970, end_year: Date.today.year %><br><br>
  <%= f.submit %>
<% end %>

app/views/users/edit.erb
<div class="profilepage">

<h1>Edit profile for <%= @user.full_name %></h1>
<%= render 'form' %>

</div>

app/views/users/new.erb
<div class="homepage">
  <h1>Sign Up Page</h1><br>

  <p>
    Hooray! Thanks for choosing to be a part of the Home Bartendr community! You're on
    your way to making your life a ton easier!
  </p><br>

  <%= render 'form' %>
</div>

app/views/users/show.erb
<div class="profilepage">

<h1>Welcome to your profile, <%= @user.full_name %>!</h1><br><br>

<h2>FAVORITES</h2>
<div>
  <% @favorites.each do |f| %>
    <li><%= link_to f.name, recipe_path(f) %></li>
  <% end %>
</div><br><br>

<h2>MY LIQUOR CABINET</h2>
<div>
  <% @ingredients.each do |i| %>
    <li><%= link_to i.name, ingredient_path(i) %></li>
  <% end %><br>
</div><br><br>

<p><%= button_to 'What can I make?', {action: 'what_can_i_make'}, method: :get %> </p>

<div class="menu">
  <li><a href=<%= recipes_path %> class="menuitem">Browse cocktails</a></li>
  <li><a href=<%= ingredients_path %> class="menuitem">Browse ingredients</a></li>
  <li> <%= link_to "Log out", logout_path, {method: :delete, :class=>"menuitem"} %> </li>
</div>

<p>
<%= button_to 'Edit profile', {action: 'edit'}, method: :get %>
</p>
<p>
<%= button_to 'Delete account', {action: 'destroy'}, method: :delete, data: {confirm: 'Are you sure?'} %>
</p>
</div>

app/views/users/what_can_i_make.erb
<div class="profilepage">

<h1>What Can I Make??</h1>

<% if @recipes != [] %>
  <% @recipes.each do |recipe| %>
    <ul>
      <%= link_to recipe.name, recipe_path(recipe) %>
    </ul>
  <% end %>
<% end %>

<%= link_to "Back to profile", user_path(current_user) %>
</div>